package com.itdaoshi.dbsource;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.List;

import org.apache.commons.dbutils.QueryRunner;
import org.apache.commons.dbutils.ResultSetHandler;
import org.apache.commons.dbutils.handlers.BeanListHandler;

public class DBTools {
  private static Connection con;

  public static synchronized Connection getSourceConnection() {
    String url = "jdbc:mysql://192.168.1.246:3306/lxsm";
    if (con != null) {
      return con;
    }
    try {
      Class.forName("com.mysql.jdbc.Driver");
      con = DriverManager.getConnection(url, "root", "root");
    } catch (Exception e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }
    return con;

  }

  public static List<SourceUser> getAllUsers() {
    ResultSetHandler h = new BeanListHandler(SourceUser.class);
    QueryRunner run = new QueryRunner();
    // Execute the SQL statement with one replacement parameter and
    // return the results in a new Person object generated by the BeanHandler.
    List<SourceUser> persons = new LinkedList<SourceUser>();
    try {
      persons = (List<SourceUser>) run.query(getSourceConnection(),
          "SELECT * FROM tkeys", h);

    } catch (SQLException e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }
    return persons;

  }

  public static void main(String[] args) {
    List<SourceUser> list = getAllUsers();
    System.out.println(list);
  }
}
