package com.itdaoshi.confluence;

import junit.framework.TestCase;

import com.itdaoshi.dbsource.SourceUser;

/**
 * The class <code>ConfluenceInsertServiceTest</code> contains tests for the
 * class {@link <code>ConfluenceInsertService</code>}
 * 
 * @pattern JUnit Test Case
 * 
 * @generatedBy CodePro at 11-4-19 H10:19
 * 
 * @author Administrator
 * 
 * @version $Revision$
 */
public class ConfluenceInsertServiceTest extends TestCase {

  /**
   * Construct new test instance
   * 
   * @param name
   *          the test name
   */
  public ConfluenceInsertServiceTest(String name) {
    super(name);
  }

  /**
   * Launch the test.
   * 
   * @param args
   *          String[]
   */

  /**
   * Run the void postNewUser(SourceUser) method test
   */
  public void testPostNewUser() {
    // add test code here
    SourceUser next = new SourceUser();
    next.setCardID("dsfsfsafsafsd");
    next.setClassName("1101");
    next.setLoginName("1101.zhangyoulin");
    next.setStudentName("уеспау");
    ConfluenceInsertService.postNewUser(next);
    assertTrue(false);
  }
}

/*
 * $CPS$ This comment was generated by CodePro. Do not edit it. patternId =
 * com.instantiations.assist.eclipse.pattern.testCasePattern strategyId =
 * com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = assertTrue = false callTestMethod = true createMain =
 * true createSetUp = false createTearDown = false createTestFixture = false
 * createTestStubs = false methods = postNewUser(QSourceUser;) package =
 * com.itdaoshi.confluence package.sourceFolder = octopus/src superclassType =
 * junit.framework.TestCase testCase = ConfluenceInsertServiceTest testClassType
 * = com.itdaoshi.confluence.ConfluenceInsertService
 */